
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath --controller statefulset -f kompose.yml.txt
    kompose.version: 1.30.0 (HEAD)
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
  creationTimestamp: null
  labels:
    io.kompose.service: gotalk-dbpost
    app: gotalk-dbpost # for cilium dashboard
  name: gotalk-dbpost
  namespace: myapps
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gotalk-dbpost
  strategy:
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/swarmnet: "true"
        io.kompose.service: gotalk-dbpost
        app: gotalk-dbpost
    spec:
      securityContext:
        runAsUser: 4261
        fsGroup: 100
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role.cola/storage
                    operator: In
                    values:
                    - ceph-local
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  # 해독되어 생성된 Secret 이름
                  name: gotalk-db-secret
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  # 해독되어 생성된 Secret 이름
                  name: gotalk-db-secret
                  key: user
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  # 해독되어 생성된 Secret 이름
                  name: gotalk-db-secret
                  key: db
            - name: PGDATA
              value: /data
            - name: UMASK
              value: "002"
            - name: TZ
              value: Asia/Seoul
          image: postgres:18.0
          name: gotalk-dbpost

          livenessProbe:
            exec:
                command:
                - /usr/bin/bash
                - '-c'
                - 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'
            failureThreshold: 7
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1

          readinessProbe:
            exec:
              command:
                - /usr/bin/bash
                - '-c'
                - 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'
            failureThreshold: 3
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1

          startupProbe:
            exec:
              command:
                - /usr/bin/bash
                - '-c'
                - 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'
            failureThreshold: 50
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 2

          ports:
            - containerPort: 5432
#              hostPort: 5432
              protocol: TCP
          resources:
            requests:
              memory: 1000Mi
          volumeMounts:
            - mountPath: /data
              name: gotalk-dbpost-hostpath0
              mountPropagation: HostToContainer
            - mountPath: /tmp
              name: gotalk-dbpost-tmpfs0
            - mountPath: /dev/shm
              name: gotalk-dbpost-tmpfs0
      restartPolicy: Always
      volumes:
        - persistentVolumeClaim:
            claimName: pvc-gotalk-db
          name: gotalk-dbpost-hostpath0
        - emptyDir:
           medium: Memory
          name: gotalk-dbpost-tmpfs0
        - emptyDir:
           medium: Memory
          name: gotalk-dbpost-tmpfs1
          # sizeLimit: "256M"


---
